<a href="https://colab.research.google.com/github/ulfiizza27/2141720052-Machine-Learning-2023/blob/main/Week%209/Praktikum4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Praktikum 4**

#### Klasifikasi dengan ANN

### **Deskripsi**

Pada praktikum kali ini, Anda diminta untuk membuat model ANN untuk mengklasifikasi potensi seorang customer akan meninggalkan perusahaan Anda atau tidak. Istirlah populer dari fenomena ini disebut sebagai 'churn'. Tingkat churn yang tinggi (chrun rate) akan berdampak tidak baik bagi perusahaan.

# **Pra Pengolahan Data**

### **Langkah 1 - Import Library**

In [1]:
!pip install tensorflow

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### **Langkah 2 - Load Data**

In [4]:
dataset = pd.read_csv('/content/drive/MyDrive/ML/data/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

Cek data (X)

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


### **Langkah 3 - Encoding Data Kategorikal**

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

Cek data (X) dengan print. Hasilnya,

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### **Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder**

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

Cek data (X) dengan print. Hasilnya,

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### **Langkah 5 - Split Data**

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### **Langkah 6 - Scaling Fitur**

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## **Membuat Model ANN**

### **Langkah 1 - Inisiasi Model ANN**

In [12]:
ann = tf.keras.models.Sequential()

### **Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama**

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### **Langkah 3 - Membuat Hidden Layer Kedua**

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### **Langkah 4 - Membuat Output Layer**

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## **Training Model**

### **Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN**

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### **Langkah 2 - Fitting Model**

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7756
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4591 - accuracy: 0.7965
Epoch 3/100
250/250 [==============================] - 2s 9ms/step - loss: 0.4425 - accuracy: 0.8016
Epoch 4/100
250/250 [==============================] - 2s 9ms/step - loss: 0.4328 - accuracy: 0.8070
Epoch 5/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4269 - accuracy: 0.8112
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4227 - accuracy: 0.8159
Epoch 7/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4192 - accuracy: 0.8190
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4159 - accuracy: 0.8189
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4124 - accuracy: 0.8227
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4083 - accura

### **Membuat Prediksi**

Diberikan informasi sebagai berikut,

- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: $ 60000
- Number of Products: 2

- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: $ 50000

Apakah customer tersebut perlu dipertahankan?

### **Modelkan Data Baru dan Buat Prediksi**


In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 107ms/step
[[False]]


Apakah hasilnya **False**?

## **Prediksi Dengan Data Testing**

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### **Cek Akurasi dan Confusion Matrix**

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513   82]
 [ 197  208]]


0.8605